"use strict";
(() => {
  const P=QuestPairProtocol,H=RustyConnectionHubProtocol,canonical=RustyConnectionHubCanonicalJson;
  const enc=new TextEncoder(),dec=new TextDecoder(),UUID=n=>`9a7b100${n}-7d6a-4b7f-9d4a-6f7c0a01000${n}`;
  const peers=[];
  const log=(slot,text)=>{const list=document.querySelector("#events");if(list.firstChild?.textContent==="No events yet.")list.replaceChildren();const li=document.createElement("li");li.textContent=`${new Date().toLocaleTimeString()} · ${slot}: ${text}`;list.prepend(li);while(list.children.length>40)list.lastChild.remove();};
  const updateAgreement=()=>{document.querySelector("#agreement").textContent=P.agreement(peers[0]?.reading,peers[1]?.reading,performance.now());document.querySelector("#capability").textContent="BLE capability bits are signed declarations. Only advertised Hub surfaces expose app controls; no camera or streaming readiness is inferred.";};
  class Peer {
    constructor(index){this.index=index;this.name=`Headset ${index+1}`;this.root=document.querySelector("#peer").content.firstElementChild.cloneNode(true);this.root.querySelector("h2").textContent=this.name;document.querySelector("#peers").append(this.root);this.generation=0;this.hubGeneration=0;this.get("connect").onclick=()=>this.connect();this.get("refresh").onclick=()=>this.read();this.get("disconnect").onclick=()=>this.disconnect();this.get("exchange").onclick=()=>this.exchange();this.get("secret").oninput=()=>{this.reading=undefined;this.get("facts").replaceChildren();this.sync();updateAgreement();};this.get("hub-connect").onclick=()=>this.hubConnect();this.get("hub-disconnect").onclick=()=>this.hubClose("Disconnected");this.sync();}
    get(c){return this.root.querySelector(`.${c}`);}
    sync(){const connected=!!this.device?.gatt?.connected;this.get("connect").disabled=!!this.busy;this.get("refresh").disabled=!connected||this.busy;this.get("disconnect").disabled=!connected;this.get("exchange").disabled=!connected||this.busy||!this.reading?.verified||this.reading.message.v!==1||performance.now()-this.reading.at>5000;}
    disconnect(){this.generation++;const device=this.device;this.device=null;device?.gatt?.disconnect();this.characteristics=null;this.reading=null;this.busy=false;this.get("secret").value="";this.get("connection").textContent="Disconnected";this.get("facts").replaceChildren();this.sync();updateAgreement();}
    async connect(){if(this.busy)return;const credential=this.get("secret").value;this.disconnect();this.get("secret").value=credential;const generation=this.generation;this.busy=true;this.sync();try{if(!navigator.bluetooth)throw Error("Web Bluetooth unavailable. Use a supported Chromium browser on HTTPS.");const device=await navigator.bluetooth.requestDevice({filters:[{services:[UUID(1)]}]});if(generation!==this.generation)return;if(peers.some(p=>p!==this&&p.device?.id===device.id))throw Error("This device is already selected in the other slot");this.device=device;device.addEventListener("gattserverdisconnected",()=>{if(this.device===device){this.disconnect();log(this.name,"BLE disconnected; old readings discarded.");}},{once:true});const server=await device.gatt.connect(),service=await server.getPrimaryService(UUID(1));const characteristics=await Promise.all([2,3,4].map(n=>service.getCharacteristic(UUID(n))));if(generation!==this.generation){device.gatt.disconnect();return;}this.characteristics=characteristics;this.get("connection").textContent=`Connected · ${device.name||"unnamed BLE device"}`;this.busy=false;await this.read();}catch(error){this.disconnect();log(this.name,error.message);}finally{if(generation===this.generation)this.busy=false;this.sync();}}
    async read(){if(this.busy||!this.characteristics)return;this.busy=true;this.sync();const generation=this.generation;try{const offer=P.decode(dec.decode(await this.characteristics[0].readValue()));const message=P.decode(dec.decode(await this.characteristics[2].readValue()));if(offer.k!=="offer"||!["status","accept"].includes(message.k)||offer.pid!==message.pid||offer.sid!==message.sid||offer.e!==message.e||offer.v!==message.v)throw Error("Offer/status identity mismatch");let verified=false;const secret=this.get("secret").value;if(secret){await P.verify(offer,secret);await P.verify(message,secret);verified=true;}if(generation!==this.generation)return;this.reading={message,offer,verified,at:performance.now()};this.renderFacts();log(this.name,verified?"Signed offer and status verified; read succeeded.":"State read; credential authentication not verified.");}catch(error){if(generation===this.generation){this.reading=null;this.get("facts").replaceChildren();}log(this.name,`Read failed: ${error.message}`);}finally{if(generation===this.generation)this.busy=false;this.sync();updateAgreement();}}
    renderFacts(){const r=this.reading,m=r.message,rows={Authentication:r.verified?"HMAC verified":"Unverified",Peer:m.pid,Session:m.sid,Epoch:m.e,Protocol:`v${m.v}`,Role:m.r};if(m.v===1){rows["Configured Wi-Fi hint"]=m.ws;rows["Declared capability bits"]=m.c;}else{rows["Observed group"]=m.g;rows["Owner address"]=m.ip;rows["Local address"]=m.li;rows["Boot identity"]=m.b;}const dl=this.get("facts");dl.replaceChildren();for(const[k,v]of Object.entries(rows)){const dt=document.createElement("dt"),dd=document.createElement("dd");dt.textContent=k;dd.textContent=String(v);dl.append(dt,dd);}this.get("ble-note").textContent=m.v===2?"v2 is read-only: this browser cannot attest a Quest-local group observation. No role impersonation.":"v1 exchange identifies this browser as a diagnostic controller; it does not pair the two headsets.";}
    async exchange(){if(this.get("exchange").disabled)return;const generation=this.generation;this.busy=true;this.sync();try{const before=this.reading,o=before.offer,m={m:"rqrv",v:1,k:"proposal",sid:o.sid,pid:"browser-diagnostic",e:o.e,q:2,r:o.r==="client"?"group_owner":"client",c:1,ws:"idle",ttl:Math.min(o.ttl,30000),n:Array.from(crypto.getRandomValues(new Uint8Array(8)),b=>b.toString(16).padStart(2,"0")).join("")};m.a=await P.auth(m,this.get("secret").value);const bytes=enc.encode(JSON.stringify(m));if(bytes.length>220)throw Error("Diagnostic payload exceeds 220-byte bound");if(generation!==this.generation)return;await this.characteristics[1].writeValueWithResponse(bytes);log(this.name,"v1 diagnostic proposal sent; awaiting readback.");this.busy=false;await this.read();log(this.name,P.diagnosticReadback(before,m,this.reading));}catch(error){log(this.name,`Exchange unconfirmed: ${error.message}`);}finally{if(generation===this.generation)this.busy=false;this.sync();}}
    hubClose(reason){this.hubGeneration++;const socket=this.socket;this.socket=null;socket?.close();clearTimeout(this.commandTimer);this.auth=null;this.projection=null;this.pending=null;this.surfaces=new Map();this.get("surfaces").replaceChildren();this.get("hub-state").textContent=reason;this.get("hub-disconnect").disabled=true;this.get("hub-connect").disabled=false;}
    hubConnect(){this.hubClose("Connecting…");let url;try{url=P.socketURL(this.get("endpoint").value);if(!/^[A-Za-z0-9_-]{32,256}$/.test(this.get("token").value))throw Error("Enter an existing Hub controller session");}catch(error){this.get("hub-state").textContent=error.message;return;}const generation=this.hubGeneration,socket=new WebSocket(url);this.socket=socket;this.get("hub-connect").disabled=true;this.get("hub-disconnect").disabled=false;const session=this.get("token").value;this.get("token").value="";socket.onopen=()=>{if(generation===this.hubGeneration)socket.send(canonical({$schema:H.schemas.socket_authenticate,type:H.types.authenticate,session}));};socket.onmessage=e=>{if(generation!==this.hubGeneration)return;try{if(typeof e.data!=="string"||enc.encode(e.data).length>65536)throw Error("Hub frame exceeds bound");this.handleHub(JSON.parse(e.data));}catch(error){this.hubClose(`Hub rejected: ${error.message}`);log(this.name,error.message);}};socket.onclose=()=>{if(generation===this.hubGeneration)this.hubClose(this.pending?"Disconnected; command outcome unknown":"Hub disconnected");};socket.onerror=()=>{if(generation===this.hubGeneration)this.hubClose("Hub connection failed. TLS/origin support may be unavailable; use the Hub local page.");};}
    handleHub(m){if(m.type===H.types.authentication_receipt){if(this.auth)throw Error("Repeated authentication receipt on active socket");this.auth=P.validateAuth(m,Date.now());this.sequence=m.next_external_request_sequence;this.get("hub-state").textContent="Controller authenticated · trusted-LAN experimental · provider controls only";return;}if(!this.auth||Date.now()>=Date.parse(this.auth.expires_at_utc))throw Error("Hub session is not authenticated or expired");if(m.type===H.types.command_receipt){const status=P.commandReceipt(m,this.pending,this.auth.transport_epoch,this.projection);clearTimeout(this.commandTimer);this.sequence=m.next_external_request_sequence;this.projection={listener_instance_id:m.listener_instance_id,surface_revision:m.surface_revision};this.pending=null;this.get("hub-state").textContent=status;log(this.name,status);this.renderSurfaces();return;}if(m.type===H.types.protocol_error)throw Error(`Hub protocol error: ${m.status}`);this.projection=P.validateProjection(m,this.auth.transport_epoch,this.projection);if(m.type===H.types.surface_snapshot){if(!Array.isArray(m.surfaces)||m.surfaces.length>32)throw Error("Invalid surface inventory");const next=new Map();for(const surface of m.surfaces){this.validateSurface(surface);if(next.has(surface.surface_id))throw Error("Duplicate surface");next.set(surface.surface_id,surface);}this.surfaces=next;}else if(m.type===H.types.surface_available){this.validateSurface(m.surface);if(this.surfaces.size>=32&&!this.surfaces.has(m.surface.surface_id))throw Error("Too many surfaces");this.surfaces.set(m.surface.surface_id,m.surface);}else if(m.type===H.types.surface_removed){this.surfaces.delete(m.surface_id);}else if(m.type===H.types.surface_state){const s=this.surfaces.get(m.surface_id);if(s){if(!Number.isSafeInteger(m.state_revision)||m.state_revision<s.state_revision)throw Error("Provider state revision regressed");s.state=P.validateState(m.state);s.state_revision=m.state_revision;}}else throw Error("Unsupported Hub message");this.renderSurfaces();}
    validateSurface(s){P.validateSurface(s);}
    renderSurfaces(){const root=this.get("surfaces");root.replaceChildren();if(!this.surfaces.size){root.textContent="No app currently offers a control surface.";return;}for(const s of this.surfaces.values()){const card=document.createElement("div");card.className="surface";const h=document.createElement("h3"),p=document.createElement("p"),state=document.createElement("p");h.textContent=s.display_label||s.surface_id;p.textContent=s.provider_package;state.textContent=JSON.stringify(s.state||{});card.append(h,p,state);for(const c of s.commands){const button=document.createElement("button");button.textContent=c.display_label;button.disabled=!!this.pending||Date.now()>=Date.parse(this.auth.expires_at_utc);button.onclick=()=>this.sendCommand(s,c);card.append(button);}root.append(card);}}
    sendCommand(s,c){if(this.pending||!this.auth||Date.now()>=Date.parse(this.auth.expires_at_utc)||this.socket?.readyState!==WebSocket.OPEN)return;const current=this.surfaces.get(s.surface_id);if(current!==s||!current.commands.includes(c))return;const frame={$schema:H.schemas.surface_command,type:H.types.surface_command,request_sequence:this.sequence,request_id:crypto.randomUUID(),surface_id:s.surface_id,command:c.command,args:{}};this.pending={...frame,projection:{...this.projection}};this.socket.send(canonical(frame));this.get("hub-state").textContent="Sent; waiting for provider-applied receipt";this.renderSurfaces();this.commandTimer=setTimeout(()=>this.hubClose("Command outcome unknown: receipt timed out. No automatic retry."),10000);}
  }
  peers.push(new Peer(0),new Peer(1));document.querySelector("#forget").onclick=()=>{for(const p of peers){p.disconnect();p.hubClose("Disconnected; credentials forgotten");p.get("secret").value="";p.get("token").value="";}log("Console","Connections closed and in-memory inputs cleared.");};setInterval(()=>{updateAgreement();for(const p of peers){p.sync();if(p.auth&&Date.now()>=Date.parse(p.auth.expires_at_utc))p.hubClose("Hub session expired");}},1000);
})();
