"use strict";
// Target-free browser integration. No real BLE, listener, app or provider effects.
const fs=require("node:fs"),path=require("node:path"),http=require("node:http"),assert=require("node:assert/strict"),crypto=require("node:crypto");
const {chromium}=require(process.argv[2]||"playwright");const output=path.resolve(process.argv[3]||"artifacts/quest-pair-browser");fs.mkdirSync(output,{recursive:true});
const root=path.resolve(__dirname,"..");const server=http.createServer((req,res)=>{const file=path.resolve(root,"."+decodeURI(req.url.split("?")[0]));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}const resolved=fs.existsSync(file)&&fs.statSync(file).isDirectory()?path.join(file,"index.html"):file;if(!fs.existsSync(resolved)){res.writeHead(404).end();return;}res.setHeader("Content-Type",resolved.endsWith(".js")?"text/javascript":resolved.endsWith(".css")?"text/css":"text/html");res.end(fs.readFileSync(resolved));});
(async()=>{await new Promise(r=>server.listen(0,"127.0.0.1",r));const url=`http://127.0.0.1:${server.address().port}/quest-pair-control/`,browser=await chromium.launch({headless:true});let cases=0;try{
const page=await browser.newPage({viewport:{width:1365,height:960}}),errors=[];page.on("pageerror",e=>errors.push(e.message));await page.goto(url);assert.match(await page.title(),/Quest pair console/);assert.equal(await page.locator("article").count(),2);assert.equal(await page.locator(".exchange:disabled").count(),2);assert.match(await page.locator("#agreement").innerText(),/Connect and read/);await page.screenshot({path:path.join(output,"desktop.png"),fullPage:true});cases++;
await page.locator("details").first().locator("summary").click();await page.locator(".endpoint").first().fill("ws://example.test/v1/socket");await page.locator(".hub-connect").first().click();assert.match(await page.locator(".hub-state").first().innerText(),/credential-free wss/);cases++;
await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,"mobile.png"),fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.deepEqual(errors,[]);cases++;
await page.close();const modeled=await browser.newPage();modeled.on("pageerror",e=>errors.push(e.message));await modeled.addInitScript(()=>{
class Socket {static OPEN=1;constructor(url){this.readyState=1;globalThis.testSocket=this;setTimeout(()=>this.onopen?.(),0);}send(raw){const m=JSON.parse(raw);(globalThis.sentFrames??=[]).push(m);if(m.type==="authenticate")setTimeout(()=>this.onmessage?.({data:JSON.stringify({$schema:"rusty.quest.connection_hub.socket_authentication_receipt.v2",type:"authentication_receipt",accepted:true,status:"authenticated",transport_epoch:2,next_external_request_sequence:1,expires_at_utc:new Date(Date.now()+60000).toISOString(),confidentiality:"none",production_eligible:false})}),0);}close(){this.readyState=3;}}
globalThis.WebSocket=Socket;globalThis.deliver=m=>testSocket.onmessage({data:JSON.stringify(m)});
});await modeled.goto(url);await modeled.locator("details").first().locator("summary").click();await modeled.locator(".endpoint").first().fill("wss://example.test/v1/socket");await modeled.locator(".token").first().fill("A".repeat(43));await modeled.locator(".hub-connect").first().click();await modeled.waitForFunction(()=>document.querySelector(".hub-state").textContent.includes("Controller authenticated"));assert.equal(await modeled.locator(".token").first().inputValue(),"");cases++;
await modeled.evaluate(()=>deliver({$schema:"rusty.quest.connection_hub.surface_snapshot.v1",type:"surface_snapshot",transport_epoch:2,listener_instance_id:"00112233445566778899aabbccddeeff",surface_revision:1,transport_classification:"trusted_lan_experimental",confidentiality:"none",production_eligible:false,surfaces:[{schema_version:1,surface_id:"surface.test",display_label:"Modelled app",description:"Target-free transport model",provider_package:"test.only",provider_signer_sha256:"a".repeat(64),surface_contract_sha256:"sha256:"+"b".repeat(64),state_revision:1,state:{running:false},commands:[{command:"command.test",display_label:"Modelled start",required_controller_capability:"control.test"}]}]}));await modeled.locator(".surface button").click();assert.match(await modeled.locator(".hub-state").first().innerText(),/waiting/);assert.equal(await modeled.locator(".surface button").isDisabled(),true);const frame=await modeled.evaluate(()=>sentFrames.at(-1));assert.equal(frame.command,"command.test");assert.deepEqual(frame.args,{});cases++;
await modeled.evaluate(frame=>deliver({...frame,$schema:"rusty.quest.connection_hub.command_receipt.v2",type:"command_receipt",transport_epoch:2,next_external_request_sequence:2,listener_instance_id:"00112233445566778899aabbccddeeff",surface_revision:1,transport_classification:"trusted_lan_experimental",confidentiality:"none",production_eligible:false,accepted:true,provider_applied:true,status:"provider_effect_observed",authority_receipt:{$schema:"rusty.manifold.connection_hub.receipt.v3",session:{$schema:"rusty.manifold.connection_hub.session.v2",session_id:"epoch-1.session.fixture",controller_id:"epoch-1.controller.fixture",opened_at_ms:1000,expires_at_ms:16000,transport_epoch:2,transport:{transport_id:"transport.hub.fixture",evidence_id:"evidence.transport.hub.fixture",attached_at_ms:1000}}}}),frame);await modeled.waitForFunction(()=>document.querySelector(".hub-state").textContent==="Provider applied");cases++;
// Native denial may retain the request sequence; this is not an applied effect.
await modeled.locator(".surface button").click();await modeled.evaluate(()=>deliver({...sentFrames.at(-1),$schema:"rusty.quest.connection_hub.command_receipt.v2",type:"command_receipt",transport_epoch:2,next_external_request_sequence:2,listener_instance_id:"00112233445566778899aabbccddeeff",surface_revision:1,transport_classification:"trusted_lan_experimental",confidentiality:"none",production_eligible:false,accepted:false,provider_applied:false,status:"command_rate_limited",authority_receipt:{}}));await modeled.waitForFunction(()=>document.querySelector(".hub-state").textContent==="Rejected or not applied");assert.equal(await modeled.locator(".surface").count(),1);assert.equal(await modeled.locator(".surface button").isDisabled(),false);cases++;
await modeled.locator(".surface button").click();await modeled.evaluate(()=>deliver({...sentFrames.at(-1),$schema:"rusty.quest.connection_hub.command_receipt.v2",type:"command_receipt",transport_epoch:2,next_external_request_sequence:3,listener_instance_id:"11223344556677889900aabbccddeeff",surface_revision:2,transport_classification:"trusted_lan_experimental",confidentiality:"none",production_eligible:false,accepted:true,provider_applied:true,status:"provider_effect_observed",authority_receipt:{}}));assert.match(await modeled.locator(".hub-state").first().innerText(),/rejected.*Unjoined/);assert.equal(await modeled.locator(".surface").count(),0);cases++;
await modeled.locator(".token").first().fill("A".repeat(43));await modeled.locator(".hub-connect").first().click();await modeled.waitForFunction(()=>document.querySelector(".hub-state").textContent.includes("Controller authenticated"));await modeled.evaluate(()=>deliver({$schema:"rusty.quest.connection_hub.socket_authentication_receipt.v2",type:"authentication_receipt",accepted:true,status:"authenticated",transport_epoch:2,next_external_request_sequence:1,expires_at_utc:new Date(Date.now()+60000).toISOString(),confidentiality:"none",production_eligible:false}));assert.match(await modeled.locator(".hub-state").first().innerText(),/Repeated authentication/);cases++; await modeled.locator("#forget").click();assert.equal(await modeled.locator(".secret").first().inputValue(),"");assert.equal(await modeled.evaluate(()=>localStorage.length+sessionStorage.length),0);assert.deepEqual(errors,[]);cases++;
const P=require("./protocol.js"),secret="temporary-modelled-secret",offer={m:"rqrv",v:1,k:"offer",sid:"session-test",pid:"quest-one",e:1760000000000,q:1,r:"group_owner",c:1,ws:"idle",ttl:30000,n:"0011223344556677"};offer.a=await P.auth(offer,secret,crypto.webcrypto);const status={...offer,k:"accept",q:3};status.a=await P.auth(status,secret,crypto.webcrypto);
await modeled.addInitScript(({offer,status})=>{const enc=new TextEncoder();const view=m=>{const bytes=enc.encode(JSON.stringify(m));return new DataView(bytes.buffer);};let accepted=false;const device={id:"model-device",name:"Modelled Quest",addEventListener(){},gatt:{connected:false,async connect(){this.connected=true;return{getPrimaryService:async()=>({getCharacteristic:async uuid=>({readValue:async()=>view(uuid.includes("1002-")?offer:status),writeValueWithResponse:async()=>{accepted=true;}})})};},disconnect(){this.connected=false;}}};Object.defineProperty(navigator,"bluetooth",{value:{requestDevice:async()=>device},configurable:true});},{offer,status});await modeled.reload();await modeled.locator(".secret").first().fill(secret);await modeled.locator(".connect").first().click();await modeled.waitForFunction(()=>document.querySelector(".facts").textContent.includes("HMAC verified"));assert.equal(await modeled.locator(".exchange").first().isDisabled(),false);await modeled.locator(".exchange").first().click();await modeled.waitForFunction(()=>document.querySelector("#events").textContent.includes("No new joined authenticated acceptance"));cases++;await modeled.locator(".disconnect").first().click();assert.equal(await modeled.locator(".facts").first().innerText(),"");assert.equal(await modeled.locator(".exchange").first().isDisabled(),true);cases++;
fs.writeFileSync(path.join(output,"result.json"),JSON.stringify({status:"passed",cases,browser:"chromium",device_effects:false,modelled_transport_cases:true,errors},null,2));console.log(`PASS ${cases} browser cases; target-free models, no device qualification`);
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
