"use strict";
(() => {
  const encode=new TextEncoder(),decode=new TextDecoder("utf-8",{fatal:true}),MAX=16384,HEADER=8;
  const uuid=n=>`9a7b300${n}-7d6a-4b7f-9d4a-6f7c0a03000${n}`;
  function fragments(text,id,mtu){const body=encode.encode(text);if(!body.length||body.length>MAX||!Number.isInteger(id)||id<1||id>65535||!Number.isInteger(mtu)||mtu<23||mtu>517)throw Error("BLE carrier bound");const size=Math.min(mtu-3,244)-HEADER,result=[];for(let offset=0;offset<body.length;offset+=size){const count=Math.min(size,body.length-offset),bytes=new Uint8Array(HEADER+count),view=new DataView(bytes.buffer);bytes[0]=1;view.setUint16(2,id);view.setUint16(4,offset);view.setUint16(6,body.length);bytes.set(body.subarray(offset,offset+count),HEADER);result.push(bytes);}return result;}
  class Assembly {
    constructor(){this.id=1;this.closed=false;this.offset=0;}
    accept(input,mtu,now){try{const bytes=new Uint8Array(input.buffer,input.byteOffset,input.byteLength),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(this.closed||bytes.length<=HEADER||bytes.length>Math.min(mtu-3,244)||!Number.isInteger(mtu)||mtu<23||mtu>517||bytes[0]!==1||bytes[1]!==0||view.getUint16(2)!==this.id||view.getUint16(4)!==this.offset)throw Error("BLE stale or reordered carrier");const total=view.getUint16(6);if(!total||total>MAX)throw Error("BLE carrier size");if(!this.offset){this.body=new Uint8Array(total);this.started=now;this.deadline=now+10000;}if(total!==this.body.length||now<this.started||now>=this.deadline||this.offset+bytes.length-HEADER>total)throw Error("BLE carrier deadline or size");this.body.set(bytes.subarray(HEADER),this.offset);this.offset+=bytes.length-HEADER;if(this.offset!==total)return null;const result=decode.decode(this.body);this.body.fill(0);this.body=null;this.offset=0;if(this.id===65535)this.closed=true;else this.id++;return result;}catch(error){this.close();throw error;}}
    close(){this.closed=true;this.body?.fill(0);this.body=null;this.offset=0;}
  }
  class HubBleSocket {
    constructor(){this.readyState=0;this.generation=0;this.id=1;this.assembly=new Assembly();this.operations=Promise.resolve();this.deadline=performance.now()+900000;this.transportLabel="Bluetooth GATT to existing Hub · confidentiality not proven";this.connect();}
    current(generation){if(this.readyState===3||generation!==this.generation||performance.now()>=this.deadline)throw Error("BLE carrier retired or expired");}
    async connect(){const generation=this.generation;try{if(!navigator.bluetooth)throw Error("Web Bluetooth unavailable");const device=await navigator.bluetooth.requestDevice({filters:[{services:[uuid(1)]}]});this.current(generation);this.device=device;device.addEventListener("gattserverdisconnected",()=>{if(this.device===device)this.close();},{once:true});const server=await device.gatt.connect();this.current(generation);const service=await server.getPrimaryService(uuid(1));[this.write,this.read,this.status]=await Promise.all([2,3,4].map(n=>service.getCharacteristic(uuid(n))));this.current(generation);await this.readStatus(generation);this.readyState=1;this.onopen?.();this.poll(generation);}catch(error){this.fail(error);}}
    operation(generation,task){const result=this.operations.then(()=>{this.current(generation);return task();});this.operations=result.catch(()=>{});return result;}
    async readStatus(generation){const raw=await this.operation(generation,()=>this.status.readValue());this.current(generation);if(raw.byteLength>512)throw Error("BLE status bound");const s=JSON.parse(decode.decode(raw));if(s.v!==1||s.carrier!=="ble_gatt_to_loopback_hub"||s.listener_observed!==true||s.controller_authority!=="not_claimed"||s.production_eligible!==false||!Number.isInteger(s.mtu)||s.mtu<23||s.mtu>517)throw Error("Actual helper/listener unavailable");this.mtu=s.mtu;}
    send(text){if(this.readyState!==1||this.sending)throw Error("BLE carrier unavailable or busy");this.sending=true;const generation=this.generation,started=performance.now();(async()=>{try{await this.readStatus(generation);const chunks=fragments(text,this.id++,this.mtu);for(const chunk of chunks){await this.operation(generation,()=>{if(performance.now()-started>=10000)throw Error("BLE write assembly expired");return this.write.writeValueWithResponse(chunk);});}this.current(generation);this.sending=false;}catch(error){this.fail(error);}})();}
    async poll(generation){try{while(this.readyState===1){this.current(generation);if(this.sending){await new Promise(resolve=>setTimeout(resolve,50));continue;}const bytes=await this.operation(generation,()=>this.read.readValue());this.current(generation);if(bytes.byteLength){const text=this.assembly.accept(bytes,this.mtu,performance.now());if(text!==null)this.onmessage?.({data:text});}await new Promise(resolve=>setTimeout(resolve,100));}}catch(error){this.fail(error);}}
    fail(error){if(this.readyState===3)return;this.close(false);queueMicrotask(()=>{this.onerror?.({message:error.message});this.onclose?.();});}
    close(notify=true){if(this.readyState===3)return;this.readyState=3;this.generation++;this.assembly.close();this.device?.gatt?.disconnect();this.device=null;this.write=this.read=this.status=null;if(notify)this.onclose?.();}
  }
  const api={fragments,Assembly,HubBleSocket};if(typeof module!=="undefined")module.exports=api;else globalThis.QuestHubBle=api;
})();
