"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),crypto=require("node:crypto");
const P=require("./protocol.js");require("./hub-protocol.js");
const secret="temporary-test-credential-only";
const message=()=>({m:"rqrv",v:1,k:"offer",sid:"session-test",pid:"quest-one",e:1760000000000,q:1,r:"group_owner",c:1,ws:"idle",ttl:30000,n:"0011223344556677",a:"0000000000000000"});
test("v1 owner-compatible HMAC bytes; changed fields deny",async()=>{const m=message();m.a=await P.auth(m,secret,crypto.webcrypto);const expected=crypto.createHmac("sha256",secret).update(P.signing(m)).digest("hex").slice(0,16);assert.equal(m.a,expected);await P.verify(P.decode(JSON.stringify(m)),secret,crypto.webcrypto);await assert.rejects(P.verify({...m,e:m.e+1},secret,crypto.webcrypto));});
test("v1 hints never become observed readiness and conflicting preferences deny",()=>{const a={message:message(),verified:true,at:100};const b={...a,message:{...message(),pid:"quest-two",r:"client"}};assert.match(P.agreement(a,b,101),/remain unproved/);assert.match(P.agreement(a,{...b,message:{...b.message,r:"group_owner"}},101),/Conflicting/);assert.match(P.agreement(a,b,6000),/stale/);assert.match(P.agreement({...a,verified:false},b,101),/not verified/);});
test("actual-shaped v2 compact array verifies separately and binds group/epoch",async()=>{const wire=["rqrv2","o","session-test","quest-one",1760000000000,1,"g","192.168.49.1","192.168.49.1","0011223344556677","aabbccddeeff0011","8899aabbccddeeff","","0000000000000000"];const m=P.decode(JSON.stringify(wire));wire[13]=await P.auth(m,secret,crypto.webcrypto);await P.verify(P.decode(JSON.stringify(wire)),secret,crypto.webcrypto);const a={message:P.decode(JSON.stringify(wire)),verified:true,at:100},b={...a,message:{...a.message,pid:"quest-two",r:"c",li:"192.168.49.2"}};assert.match(P.agreement(a,b,101),/observed group fields agree/);for(const damaged of [{g:"1122334455667788"},{e:1},{r:"g"},{pid:a.message.pid}])assert.doesNotMatch(P.agreement(a,{...b,message:{...b.message,...damaged}},101),/fields agree/);assert.throws(()=>P.decode(JSON.stringify(wire)+" "));});
test("wire size, unknown keys, invalid capability and Wi-Fi fields deny",()=>{for(const mutate of [m=>m.extra=true,m=>m.c=17,m=>m.ws="pretend",m=>m.ip="192.168.49.1",m=>m.pid="x".repeat(33)]){const m=message();mutate(m);assert.throws(()=>P.decode(JSON.stringify(m)));}assert.throws(()=>P.decode(" ".repeat(245)));});
const auth=()=>({$schema:"rusty.quest.connection_hub.socket_authentication_receipt.v2",type:"authentication_receipt",accepted:true,status:"authenticated",transport_epoch:2,next_external_request_sequence:1,expires_at_utc:"2030-01-01T00:00:00Z",confidentiality:"none",production_eligible:false});
test("Hub requires explicit authenticated bounded session, not socket open",()=>{assert.equal(P.validateAuth(auth(),0).transport_epoch,2);for(const changes of [{accepted:false},{expires_at_utc:"bad"},{expires_at_utc:"1970-01-01"},{next_external_request_sequence:0},{production_eligible:true}])assert.throws(()=>P.validateAuth({...auth(),...changes},1));for(const url of ["ws://host/v1/socket","wss://secret@host/v1/socket","wss://host/other","wss://host/v1/socket?token=secret"])assert.throws(()=>P.socketURL(url));assert.equal(P.socketURL("wss://example.test/v1/socket"),"wss://example.test/v1/socket");});
test("command outcome requires exact joined provider receipt; ACK alone never applied",()=>{const projection={listener_instance_id:"00112233445566778899aabbccddeeff",surface_revision:1};const pending={projection,request_id:"r1",request_sequence:1,surface_id:"surface.test",command:"command.test"};const receipt={$schema:"rusty.quest.connection_hub.command_receipt.v2",type:"command_receipt",...pending,transport_epoch:2,next_external_request_sequence:2,listener_instance_id:"00112233445566778899aabbccddeeff",surface_revision:1,transport_classification:"trusted_lan_experimental",confidentiality:"none",production_eligible:false,accepted:true,provider_applied:true,status:"provider_effect_observed",authority_receipt:{}};assert.equal(P.commandReceipt(receipt,pending,2,projection),"Provider applied");assert.equal(P.commandReceipt({...receipt,provider_applied:false},pending,2,projection),"Rejected or not applied");for(const changes of [{request_id:"other"},{transport_epoch:3},{surface_id:"other"},{request_sequence:2},{next_external_request_sequence:5},{listener_instance_id:"bad"}])assert.throws(()=>P.commandReceipt({...receipt,...changes},pending,2,projection));assert.throws(()=>P.commandReceipt(receipt,null,2));});
test("reused Hub canonical encoder retains published command vector",()=>{const frame={$schema:"rusty.quest.connection_hub.surface_command.v2",args:{},command:"command.example.play",request_id:"request.example.1",request_sequence:1,surface_id:"surface.example.controls",type:"surface.command"};const bytes=RustyConnectionHubCanonicalJson(frame);assert.equal(crypto.createHash("sha256").update(bytes).digest("hex"),"6cc14780d7cbe3c4d7ba5dcb2d39a7d4fe0dee95ec0bcb01bab84e263d90d69f");});
test("surface inventory joins authenticated epoch/listener and monotonic revision",()=>{const m={$schema:"rusty.quest.connection_hub.surface_snapshot.v1",type:"surface_snapshot",transport_epoch:2,listener_instance_id:"00112233445566778899aabbccddeeff",surface_revision:2,transport_classification:"trusted_lan_experimental",confidentiality:"none",production_eligible:false};const previous=P.validateProjection(m,2,null);for(const change of [{transport_epoch:3},{listener_instance_id:"11223344556677889900aabbccddeeff"},{surface_revision:1},{$schema:"unknown"},{confidentiality:"tls"}])assert.throws(()=>P.validateProjection({...m,...change},2,previous));});
test("v1 acceptance observation denies retained nonce/sequence and changed identities, never claims nonce acknowledgement",()=>{const before={verified:true,message:{...message(),k:"accept",q:3}},sent={...message(),pid:"browser-diagnostic",k:"proposal",q:2,r:"client",n:"8899aabbccddeeff"},after={verified:true,message:{...before.message,n:"1122334455667788"}};assert.match(P.diagnosticReadback(before,sent,after),/exact acknowledgement is unavailable/);for(const changes of [{n:before.message.n},{q:2},{sid:"other-session"},{e:1},{pid:"other-peer"},{r:"client"},{v:2}])assert.throws(()=>P.diagnosticReadback(before,sent,{...after,message:{...after.message,...changes}}));});
test("command receipt must join current and sent listener/revision; revision may advance",()=>{const projection={listener_instance_id:"00112233445566778899aabbccddeeff",surface_revision:3},pending={projection,request_id:"r1",request_sequence:1,surface_id:"surface.test",command:"command.test"};const receipt={$schema:"rusty.quest.connection_hub.command_receipt.v2",type:"command_receipt",...pending,transport_epoch:2,next_external_request_sequence:2,listener_instance_id:projection.listener_instance_id,surface_revision:4,transport_classification:"trusted_lan_experimental",confidentiality:"none",production_eligible:false,accepted:true,provider_applied:true,status:"provider_effect_observed",authority_receipt:{}};assert.equal(P.commandReceipt(receipt,pending,2,projection),"Provider applied");assert.throws(()=>P.commandReceipt({...receipt,surface_revision:2},pending,2,projection));assert.throws(()=>P.commandReceipt({...receipt,listener_instance_id:"11223344556677889900aabbccddeeff"},pending,2,projection));assert.throws(()=>P.commandReceipt(receipt,pending,2,{...projection,surface_revision:5}));});

test("v1 strict numeric carrier types and owner IPv4/capability boundaries",()=>{for(const change of [{ttl:undefined},{ttl:null},{ttl:"30000"},{ttl:"NaN"},{ttl:999},{ttl:120001},{ttl:1.5},{c:4294967297},{c:-1},{c:16},{c:"1"},{c:5}])assert.throws(()=>P.decode(JSON.stringify({...message(),...change})));for(const ttl of [1000,120000])assert.equal(P.decode(JSON.stringify({...message(),ttl})).ttl,ttl);for(const ip of ["192.168.49.0","192.168.49.255","192.168.49.999","192.168.43.1"])assert.throws(()=>P.decode(JSON.stringify({...message(),ws:"grouped",ip})));for(const ip of ["192.168.49.1","192.168.137.254"])assert.equal(P.decode(JSON.stringify({...message(),ws:"grouped",ip})).ip,ip);assert.throws(()=>P.decode(JSON.stringify({...message(),ws:"ready",ip:"192.168.49.1",bp:8080,c:9})));assert.equal(P.decode(JSON.stringify({...message(),ws:"ready",ip:"192.168.49.1",bp:65535,c:15})).bp,65535);});

test("actual owner fractional playlist state stays scalar and bounded",()=>{const state={active_index:0,active_label:"Current profile",item_count:2,item_duration_seconds:10,item_elapsed_seconds:2,paused:false,phase:"playing",playlist_title:"Review fixture",progress:0.25,revision:3,running:true};assert.equal(P.validateState(state).progress,0.25);for(const progress of [NaN,Infinity,-Infinity,Number.MAX_SAFE_INTEGER+1])assert.throws(()=>P.validateState({...state,progress}));assert.throws(()=>P.validateState({nested:{progress:0.25}}));assert.throws(()=>P.validateState(Object.fromEntries(Array.from({length:17},(_,i)=>["k"+i,0]))));assert.throws(()=>P.validateState(Object.fromEntries(Array.from({length:16},(_,i)=>["k"+i,"\u4e00".repeat(256)]))));const surface={schema_version:1,surface_id:"surface.test",display_label:"Playlist",description:"Current owner fixture",surface_contract_sha256:"sha256:"+"a".repeat(64),provider_package:"io.example.provider",provider_signer_sha256:"b".repeat(64),commands:[],state,state_revision:3};assert.equal(P.validateSurface(surface).state.progress,0.25);for(const state_revision of [0.25,Number.MAX_SAFE_INTEGER+1])assert.throws(()=>P.validateSurface({...surface,state_revision}));});

// Public session identity is owner receipt data, never the opaque authentication cookie.
test("actual native-shaped public session and effect status; honest denied sequence",()=>{
  const projection={listener_instance_id:"00112233445566778899aabbccddeeff",surface_revision:3};
  const pending={projection,request_id:"request.fixture.1",request_sequence:1,surface_id:"surface.concurrent_stereo.controls",command:"command.concurrent_stereo.own"};
  const authority={$schema:"rusty.manifold.connection_hub.receipt.v3",request_id:"epoch-1.request.requestfixture1",operation:"authorize_surface_command",applied:true,next_external_request_sequence:2,session:{$schema:"rusty.manifold.connection_hub.session.v2",session_id:"epoch-1.session.fixture",controller_id:"epoch-1.controller.fixture",opened_at_ms:1000,expires_at_ms:16000,transport_epoch:2,transport:{transport_id:"transport.hub.fixture",evidence_id:"evidence.transport.hub.fixture",attached_at_ms:1000}},command_authorization:{$schema:"rusty.manifold.connection_hub.command_authorization.v2",request_id:"epoch-1.request.requestfixture1",transport_epoch:2,provider_id:"provider.quest.concurrent-stereo",provider_instance_id:"epoch-1.provider.fixture",surface_id:"epoch-1.provider.fixture.surface-instance.surface.concurrent_stereo.controls",command_id:"command.concurrent_stereo.own",proves_application_effect:false}};
  const receipt={$schema:"rusty.quest.connection_hub.command_receipt.v2",type:"command_receipt",...pending,transport_epoch:2,next_external_request_sequence:2,listener_instance_id:projection.listener_instance_id,surface_revision:4,transport_classification:"trusted_lan_experimental",confidentiality:"none",production_eligible:false,accepted:true,provider_applied:true,status:"provider_effect_observed",authority_receipt:authority};
  assert.equal(P.commandReceipt(receipt,pending,2,projection),"Provider applied");
  assert.equal(receipt.authority_receipt.session.session_id,"epoch-1.session.fixture");
  for(const next_external_request_sequence of [1,2])assert.equal(P.commandReceipt({...receipt,accepted:false,provider_applied:false,status:"command_rate_limited",next_external_request_sequence,authority_receipt:{}},pending,2,projection),"Rejected or not applied");
  for(const change of [{accepted:false},{status:"provider_applied"},{status:"provider_effect_queued"},{request_id:"retained"},{request_sequence:true},{next_external_request_sequence:0},{next_external_request_sequence:3},{listener_instance_id:"11223344556677889900aabbccddeeff"}])assert.throws(()=>P.commandReceipt({...receipt,...change},pending,2,projection));
  assert.throws(()=>P.commandReceipt({...receipt,accepted:false,provider_applied:false,next_external_request_sequence:3},pending,2,projection));
  assert.equal(P.commandReceipt({...receipt,provider_applied:false,status:"provider_effect_queued"},pending,2,projection),"Rejected or not applied");
});
